= Code of conduct


Все материалы на этом сайте являются открытыми и доступны всем. При их использовании ознакомьтесь с лицензией https://www.mozilla.org/en-US/MPL/2.0/[MPL-2.0], под которой распространяется проект.

== Open-source education

Проект придерживается концепции _open-source education_: все материалы предоставляются всем на без возмездной основе при выполнении условий лицензии.
Мы не запрещаем использовать наш источник в коммерческих и монетизируемых проектах, однако обязуем использующих предоставлять ссылку на наш источник, где каждый сможет получить бесплатный доступ.

== AI

Проект не одобряет использование AI как источника информации для обучения из-за его архитектурных особенностей. Поэтому все материалы представленные на сайте должны быть составлены *исключительно людьми*! Не допускается публикация сгенерированных текстов, примеров кода, фото и видеоматериалов. Исключение делается только для демонстрации результатов работы ИИ в статьях про ИИ инструменты. Однако авторам разрешается использовать ИИ для формирования плана статьи или как средство проверки и валидации контента. *Важно*: итоговое решение должно оставаться за человеком.

== Заимствование источников

При написании статей не допускается копипаста чужих текстов, материалов. Любые фото/видеоматериалы рекомендуется создавать самому: например, для диаграмм можно использовать https://draw.io[draw.io], в случае использования чужих материалов цитирование источников *обязательно*.

== Нелитературная лексика

В проекте допускается использование "программистского сленга", транслитерации терминов, однако русификация _настоятельно не рекомендуется_. Например, использование слова "нити" не будет одобрено маинтейнерами проекта, а слово "поток" лучше заменить на "тред". Аналогично будет предпочтительным использование слов "мержить" и "ребейзить" вместо попытки перевести это все на русский язык. Для тех, кто не разделяет подобный подход, в качестве компромисса предлагаем использование английских слов на латинице прямо в тексте.
