= Config
:page-authors: Виктория Попова, Иван Калинин
:description: Git. Конфигурация

Git поддерживает настройку определенных параметров. Проверить все текущие настройки можно следующим образом:

[,console]
----
$ git config --list
----

== Первичная настройка Git

Сразу после установки Git нужно один раз представиться - эти данные будут вписываться в каждый ваш коммит:

[,console]
----
$ git config --global user.name "Ivan Ivanov"
$ git config --global user.email "ivan@example.com"
----

Флаг `--global` означает «для всех репозиториев этого пользователя». Если для какого-то конкретного проекта нужно другое имя или почта (например, рабочая), запустите те же команды с флагом `--local` внутри папки проекта - тогда настройки сохранятся только для него.

== Уровни конфигурации

Настройки Git лежат в обычных ini-файлах на трёх уровнях:

[cols="1,2,3"]
|===
|Флаг |Где лежит |Для кого

|`--system`
|`/etc/gitconfig` (в Windows - в папке установки Git)
|Все пользователи машины. Менять обычно нужно под `sudo`.

|`--global`
|`~/.gitconfig` или `~/.config/git/config`
|Все репозитории текущего пользователя.

|`--local`
|`.git/config` внутри репозитория
|Только этот репозиторий. Значение по умолчанию, если флаг не указан.
|===

Уровни накладываются друг на друга сверху вниз: чем ближе настройка к репозиторию, тем она важнее. Локальный `user.email` перебьёт глобальный, глобальный - системный.

Файлы можно править и руками, это простой текст:

[,ini]
----
[user]
	name = Ivan Ivanov
	email = ivan@example.com
[init]
	defaultBranch = main
----

Посмотреть, откуда взялось каждое значение (очень выручает, когда коммиты внезапно уходят не с той почты):

[,console]
----
$ git config --list --show-origin           <1>
file:/etc/gitconfig     core.autocrlf=input
file:/home/user/.gitconfig      user.name=Ivan Ivanov
file:/home/user/.gitconfig      user.email=ivan@example.com
file:.git/config        user.email=ivan@work.com

$ git config --show-origin user.email       <2>
file:.git/config        ivan@work.com

$ git config --local --unset user.email     <3>
----
<1> Все настройки с указанием файла, из которого они прочитаны.
<2> Итоговое значение одного параметра и его источник.
<3> Убрать переопределение на уровне репозитория.

Полезно также задать имя ветки по умолчанию и включить цветной вывод:

[,console]
----
$ git config --global init.defaultBranch main
$ git config --global color.ui auto
----

== Настройка цифровой подписи

Если хотите по умолчанию подписывать все коммиты, то можно настроить следующей командой:

[,console]
----
$ git config --global user.signingkey <KEY_ID>
----

`KEY_ID` можно получить из `gpg --list-keys`

== Read more

* xref:utils/gpg.adoc[]
