= Config
:page-authors: Виктория Попова, Иван Калинин
:description: Git. Конфигурация

Гит поддерживает настройку определенных параметров. Проверить все текущие настройки можно следующим образом:

[,console]
----
$ git config --list
----

== Первичная настройка git

Сразу после установки git нужно один раз представиться - эти данные будут вписываться в каждый ваш коммит:

[,console]
----
$ git config --global user.name "Ivan Ivanov"
$ git config --global user.email "ivan@example.com"
----

Флаг `--global` означает «для всех репозиториев этого пользователя». Если для какого-то конкретного проекта нужно другое имя или почта (например, рабочая), запустите те же команды без `--global` внутри папки проекта - тогда настройки сохранятся только для него.

Полезно также задать имя ветки по умолчанию и включить цветной вывод:

[,console]
----
$ git config --global init.defaultBranch main
$ git config --global color.ui auto
----

== Настройка цифровой подписи

Если хотите по умолчанию подписывать все коммиты, то можно настроить следующей командой:

[,console]
----
$ git config --global user.signingkey <KEY_ID>
----

`KEY_ID` можно получить из `gpg --list-keys`

== Read more

* xref:utils/gpg.adoc[]
