= Merge conflicts
:page-authors: Виктория Попова
:description: Git. Мерж конфликты



== Мерж-конфликты: как это работает изнутри

При merge Git ищет *общего предка* двух веток (base) и смотрит, как изменился файл в каждой ветке относительно этого base.

Три случая:

. В одной ветке файл изменился, в другой нет - берётся изменённая версия. Никакого конфликта.
. В обеих ветках файл изменился, но в *разных местах* - Git применяет оба набора изменений. Тоже без конфликта, это называется *auto-merge*.
. В обеих ветках изменена *одна и та же строка* (или соседние) - Git не знает, какой вариант правильный, и объявляет конфликт.

Конфликтные места помечаются в файле:

[,text]
----
<<<<<<< HEAD
print("Hello, world!")
=======
print("Привет, мир!")
>>>>>>> feature-x
----

* Между `<<<<<<< HEAD` и `=======` - ваш вариант.
* Между `=======` и `>>>>>>> feature-x` - вариант из ветки feature-x.

Как разрешить:

. Открываете файл, руками выбираете нужный вариант (или комбинируете), удаляете все три маркера.
. `git add FILE` - сообщить Git, что конфликт разрешён.
. `git commit` - завершить merge.

Если запутались и хотите откатить всё:

[,console]
----
$ git merge --abort           <1>
$ git rebase --abort           <2>
----
<1> Отменить незавершённый merge.
<2> То же для незавершённого rebase.

TIP: Очень полезная опция - включить трёхсторонний вид конфликтов:
+
[,console]
----
$ git config --global merge.conflictstyle diff3
----
+
После этого маркеры будут выглядеть так:
+
[,text]
----
<<<<<<< HEAD
print("Hello, world!")
||||||| merged common ancestors
print("hello")
=======
print("Привет, мир!")
>>>>>>> feature-x
----
+
Средний блок - оригинальная строка до расхождения. Гораздо проще понять, что каждая ветка меняла.
