= Stash
:page-authors: Виктория Попова
:description: Git. Stash

Ситуация: вы работаете над задачей, у вас куча несохраненных изменений, и тут срочно нужно переключиться на другую ветку и что-то починить. Коммитить пока рано (код не готов), а изменения потерять нельзя.

В лоб переключиться не выйдет - Git не даст затереть несохраненные правки:

[,console]
----
$ git switch main
error: Your local changes to the following files would be overwritten by checkout:
        app/login.py
        app/models.py
Please commit your changes or stash them before you switch branches.
Aborting
----

Тут спасает `stash`:

[,console]
----
$ git stash                          <1>
$ git switch main                    <2>
# ... делаем срочные дела, коммитим ...
$ git switch feature-x               <3>
$ git stash pop                      <4>
----
<1> Спрятать все изменения (рабочая директория чистая).
<2> Переключиться на другую ветку и работать там.
<3> Вернуться на свою задачу.
<4> Вернуть спрятанные изменения обратно.

Другие полезные команды:

[,console]
----
$ git stash list                     <1>
$ git stash show                     <2>
$ git stash apply                    <3>
$ git stash drop                     <4>
$ git stash push -m "wip: login"     <5>
$ git stash push path/to/file.py     <6>
----
<1> Что у нас в загашнике.
<2> Какие файлы изменены в последнем stash.
<3> Применить, но не удалять из stash.
<4> Удалить последний stash.
<5> Спрятать с сообщением - потом легче найти.
<6> Спрятать только один файл.

Stash - штука отдельная, не привязанная к ветке. Можно спрятать в одной, применить в другой.
