= Submodules
:page-authors: Виктория Попова, Иван Калинин
:description: Git. Сабмодули

Иногда нужно включить один Git-репозиторий в состав другого  --  например, общую библиотеку, которая живет отдельно. Для этого есть *сабмодули*:

[,console]
----
$ git submodule add PROJECT_URL libs/library
----

Внутри вашего репозитория появится папка `libs/library` с содержимым другого репозитория, а сам факт «здесь сабмодуль на такой-то коммит такого-то репозитория» запишется в файл `.gitmodules` (его надо закоммитить).

Клонирование репозитория с сабмодулями:

[,console]
----
$ git clone --recurse-submodules PROJECT_URL
 или, если забыли:
$ git submodule update --init --recursive
----

Обновить сабмодули до свежих версий из их удаленных репозиториев:

[,console]
----
$ git submodule update --remote
----

CAUTION: Если не использовать специальные опции (см. выше) при работе с репозиториями, использующими сабмодули, то папки, отвечающие сабмодулям, будут пустыми.

== Git reference files

С точки зрения гита папки, отвечающие сабмодулям,  --  это отдельный вид файлов. Гит помечает у себя во внутреннем дереве, что это другой проект, а также сохраняет *хэш коммита*, в котором сейчас находится подрепозиторий.

Такие файлы хранят информацию только о коммите, а об источнике  --  нет. Поэтому, запустив `git clone` внутри проекта, гит запомнит, что у вас есть внутренний гит-подпроект, но как его найти нет: эта информация сохраняется в `.gitmodules`. И уже ей управляет `git submodules`.

Из этого также стоит помнить, что сабмодуль завязывается на конкретный коммит, поэтому любые изменения в нем не будут отражены при `git fetch`. Для его обновления используйте команду, рассказанную выше.

TIP: Не используйте сабмодули, если ваш язык программирования имеет свои инструменты по управлению зависимостями. Сабмодули достаточно муторная и нетревиальная фича, которую часто обходят стороной из-за сложности, однако в отсутствии альтернатив она очень выручает.

== Read more

// TODO: сделать анкор на конкретную секцию
* xref:git/special-files.adoc[.gitmodules файл]
