= Compilation
:page-authors: Виктория Попова
:description: Сборка C и C++. Этап компиляции и ассемблерный вывод

== Шаг 2. Компиляция

На вход приходит чистый C++ без директив, на выход уходит ассемблер. Внутри происходит примерно следующее: лексический анализ (текст режется на токены), синтаксический анализ (строится дерево разбора), семантический анализ (проверяются типы, разрешаются перегрузки, инстанцируются шаблоны), оптимизация, генерация кода.

Для нас важен наблюдаемый результат:

[,console]
----
$ g++ -S -O0 -masm=intel main.cpp -o main.s   <1>
$ cat main.s
----
<1> `-masm=intel` переключает синтаксис с ATT на интеловский, который читается заметно легче. Флаг только для gcc и clang.

Простая функция:

[,cpp]
----
int add(int a, int b) {
    return a + b;
}
----

Превращается примерно в такое:

[,text]
----
_Z3addii:
        push    rbp
        mov     rbp, rsp
        mov     DWORD PTR [rbp-4], edi
        mov     DWORD PTR [rbp-8], esi
        mov     edx, DWORD PTR [rbp-4]
        mov     eax, DWORD PTR [rbp-8]
        add     eax, edx
        pop     rbp
        ret
----

Сравните с тем, что выдаст `-O2`: почти наверняка останется `lea eax, [rdi+rsi]` и `ret`, потому что оптимизатор выкинет пролог, эпилог и работу со стеком. Это хороший способ на глаз понять, что делает уровень оптимизации.

TIP: Не обязательно ставить компилятор локально, чтобы посмотреть на ассемблер. Есть https://godbolt.org[Compiler Explorer], где можно сравнить вывод десятков компиляторов и версий рядом, с подсветкой соответствия строк исходника и ассемблера.
