= RPM пакеты
:page-authors: Иван Калинин

Дистрибутивы Red Hat семейства используют пакетный менеджер `rpm`. На базе него есть пакетные менеджеры `yum` и `dnf`.

== Rpmbuild

Для разработки `rpm` пакетов используется директория `~/rpmbuild`. Ее можно автоматически настроить с помощью команды `rpmdev-setuptree` из `rpmdevtools` или вручную:

[,text]
----
🖿 /home/USER/rpmbuild
├─ 🖿 BUILD
├─ 🖿 RPMS
├─ 🖿 SOURCES
├─ 🖿 SPECS
└─ 🖿 SPRMS
----

* `BUILD` -- директория в которой происходит сборка пакетов
* `RPMS` -- директория для хранения `rpm`-пакетов
* `SOURCES` -- директория для хранения архивов с исходниками для использования при сборке пакетов
* `SPECS` -- директория для хранения `spec`-файлов
* `SRPMS` -- директория для хранения `srpm`-пакетов

== Spec файлы

Для создания своего `rpm`-пакета необходимо создать архив с исходниками и файл описания сборки пакета. Последний должен иметь имя `<PACKAGE NAME>.spec`. Его можно создать как вручную в папке `SPECS`, так и выполнив команду `rpmdev-newspec <PACKAGE NAME>`. Рассмотрим основные компоненты спецификации:

Преамбула::
[%autowidth]
|===
| `Name` | Название пакета
| `Version` | Версия исходного кода
| `Release` | Номер релиза, newspec по дефолту выставит `1%{?dist}`
| `Summary` | Краткое описание проекта
| `License` | Лицензия под которой распространяется проект
| `URL` | URL сайта проекта
| `Source` | URL исходников кода, используемых при сборке
| `BuildRequires` | Зависимости, необходимые для сборки пакета
| `Requires` | Рантайм зависимости
| `BuildArch` | Под какую архитектуру собран проект
|===

Тело::
[%autowidth]
|===
| `%description` | Подробное описание проекта
| `%prep` | Скрипт подготовки исходников к сборке
| `%build` | Скрипт сборки проекта
| `%install` | Скрипт установки проекта в `%\{buildroot}`
| `%files` | Индекс файлов, которые будут установлены
| `%changelog` | Описания изменений проекта
|===

Для удобства можно использовать макросы: `%\{name}`. *Важно!* Они раскрываются на этапе сборки. Объявить макрос можно через конструкции:

* `%define NAME VALUE` -- доступен только внутри одного блока
* `%global NAME VALUE` -- доступен во всем `spec`-файле

Проверить же значение макроса можно через `rpm --eval %\{MACRO_NAME}`.

Зависимости проекта описываются через запятую и для контроля версий можно использовать модификаторы `=`, `>`, `<`, `>=`, `\<=`. Например, если пакет зависит от `bash` версии хотя бы 5 и `curl`, то будет такая строчка: `Requires: bash >= 5.0.0, curl`.

== Сборка пакета

Пусть уже есть такая структура `~/rpmbuild`:

[,text]
----
🖿 ~/rpmbuild
├─ 🖿 BUILD
├─ 🖿 RPMS
├─ 🖿 SOURCES
│  └─ 🗃package-src.tar.gz
├─ 🖿 SPECS
│  └─ 🖹 package.spec
└─ 🖿 SPRMS
----

Тогда, чтобы собрать пакет, достаточно запустить команду `rpmbuild -ba ~/rpmbuild/SPECS/package.spec`. Флаг `-b` означает, что мы будем собирать пакет, а параметр `a` -- собрать и `rpm`, и `src.rpm`.

Описание сборки происходит внутри секции `%build`. Чтобы разархивировать и настроить окружение для сборки пакета используется http://ftp.rpm.org/max-rpm/s1-rpm-inside-macros.html#S2-RPM-INSIDE-SETUP-MACRO[макрос `%setup`]:

[,rpmspec]
----
%prep
%setup -q
----

Так, для сборки будет создана директория внутри `~/rpmbuild/BUILD`, в которой и будет происходить дальнейшая сборка. В случае успешной сборки `rpmbuild` удалит ее, иначе же можно пойти дебажить. В созданную директорию `%setup` разархивирует исходники указанные в `SourceN`. Если указанный путь в `Source` является относительным, то в качестве опорной директории будет выбрана `~/rpmbuild/SOURCES`.

NOTE: У проекта может быть несколько архивов с исходниками. Тогда они указываются как `Source0`, `Source1`, ...

== Установка пакета

Установка пакета -- это скрипт, описывающий то, как надо расположить файлы внутри `%\{buildroot}`, как если бы это была корневая папка системы.

TIP: Вместо явных путей используйте макросы (`%\{_bindir}`, `%\{_sysconfdir} и другие).

Если же необходимо выполнить дополнительные действия, то существуют блоки `%pre` и `%post` -- скрипты, выполняемые до и после _установки пакета в системе_ (не путать с установкой в `%\{buildroot}`). Аналогично существуют `%preun` и `%postun`, но используемые при удалении пакета. Важно отметить, что обновление пакета (`dnf update`) является удалением старой версии и установкой новой, поэтому важно уметь определять, какой именно сейчас этап. Для этого передается дополнительная информация через `$1`:

[%autowidth]
|===
h| h| Install h| Upgrade h| Uninstall
| `%pre` | `1` | `2` | _N/A_
| `%post` | `1` | `2` | _N/A_
| `%preun` | _N/A_ | `1` | `0`
| `%postun` | _N/A_ | `1` | `0`
|===


== Управление файлами

Все файлы, указанные в `%files`, будут отмечены в `rpm` как файлы, управляемые пакетным менеджером. Именно этот список файлов будет использоваться при удалении.

// TODO
[TIP.todo]
====
Добавить ссыль на страницу с глобами
====

При написании `%files` можно использовать глобы, как в терминале.

Если вам нужно указать параметры файла (разрешения, владельцы) при установке можно использовать `%attr(<FILE MODE>, <OWNER>, <OWNER GRP>) <FILENAME>`. Если указать `-`, то будут использованы дефолтные настройки (`-` -- разрешения файлов после сборки пакета, `root`, `root`).

IMPORTANT: Указание владельцев создает по умолчанию зависимости: `user(<NAME>)` или `group(<USER>)`. Чтобы игнорировать автоматическое добавление зависимостей можно добавить аттрибут `AutoReq: no`.

Для настройки дефолтных параметров существует конструкция `%defattr(<FILE MODE>, <OWNER>, <OWNER GRP>, <DIR MODE>)`. После этого указанные параметры начинают действовать на все директивы ниже.

Rpm предоставляет дополнительные проверки на основании вида файла. Последнее можно указать следующим образом:

* `%config` -- Конфиги
* `%doc` -- Документация проекта
* `%readme` -- README проекта
* `%license` -- Лицензия проекта
* `%dir` -- Папка, которая полностью управляется проектом (будет удалена при удалении пакета)
* `%ghost` -- Игнорируемые файлы (не будут установлены)






== Read more

* https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/packaging_and_distributing_software/packaging-software_packaging-and-distributing-software[RPM documentation (C) Red Hat]
* https://docs.fedoraproject.org/en-US/packaging-guidelines/RPMMacros/[Predefined macros (C) Fedora docs]
* https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/[Scriplets (C) Fedora docs]
* http://ftp.rpm.org/max-rpm/[Maximum RPM (C) Edward C. Bailey]
