#! /usr/bin/env bash

cat <<- 'EOF' > .git/hooks/pre-commit
root_dir=$(git rev-parse --show-toplevel)
"${root_dir}/scripts/dash-lint"
"${root_dir}/scripts/playbook-lint"
EOF

chmod +x .git/hooks/pre-commit
