= Хэш функции
:page-authors: Иван Калинин
:description: Хэш функции. SHA

Хэш функция определяется как отображение stem:[h: \mathbb{B}^\ast \to \mathbb{B}^n] (принимает произвольное число битов и возвращает ровно stem:[n]). Дополнительно требуется наличие следующих свойств:

* *Детерминизм*: для каждого stem:[m] значение stem:[h(m)] всегда будет одинаковым
* *Необратимость*: по значению stem:[h(m)] вычислительно сложно восстановить stem:[m] (лучше, чем перебором не получится)
* *Слабая устойчивость к коллизиям*: для фиксированного stem:[m_1] вычислительно сложно найти такое stem:[m_2], что stem:[h(m_1) = h(m_2)]
* *Сильная устойчивость к коллизиям*: вычислительно сложно найти такие stem:[m_1] и stem:[m_2], что stem:[h(m_1) = h(m_2)]
* *Равномерная распределенность значений*: вероятность получить каждое значение почти совпадают, т.е.stem:[ |\text{Pr}_m[x = h(m)\] - \frac{1}{2^n}| < \frac{1}{poly(n)} ]

Популярные хэш-фукнции:

* `MD5` генерирует 128-битный хэш. Это алгоритм, позволяющий быстро вычислить хэш, однако является небезопасным.
* `SHA1` генерирует 160-битный хэш. Этот алгоритм признан небезопасным и более не используется
* `SHA2` семейство алгоритмов, являющихся усовершенствованием `SHA1`
** `SHA224` генерирует 224-битный хэш
** `SHA256` генерирует 256-битный хэш
** `SHA384` генерирует 384-битный хэш
** `SHA512` генерирует 512-битный хэш

В терминале для вычисления хэш-функций есть утилита `shasum`. Чтобы выбрать алгоритм, необходимо передать флаг `-a <TYPE>` (1, 224, 256, 384, 512)
