= Асимметричное шифрование
:page-authors: Иван Калинин
:description: Алгоритмы асимметричного шифрования

Для создания протокола асимметричного шифрования нужны следующие компоненты:

* stem:[e] -- Ключ шифрования (он же _публичный ключ_)
* stem:[d] -- Ключ дешифрования (он же _приватный ключ_)
* stem:[E] -- Функция шифрования: stem:[E(e, m) = c]
* stem:[D] -- Функция дешифрования: stem:[D(d, c) = m]

Также от системы ожидается, что зная stem:[e] и stem:[E] обратить stem:[f(x) := E(e, x)] за разумное время нельзя. Т.е. ничего лучше полного перебора, который займет экспоненциальное время, не придумано.

NOTE: На самом деле вся криптография работает на предположении stem:[NP \ne P], что и означает существование такого рода функций. Однако, это утверждение остается недоказанным, поэтому в случае обратного (stem:[NP = P]) на это все можно забить :)

Как работает протокол:

. Генерируется пара stem:[\langle e, d \rangle]
. Публичный ключ stem:[e] отправляется второму пользователю
. Второй пользователь шифрует сообщение (stem:[m |-> E(e, m) = c]) и отправляет шифрограмму
. Первый расшифровывает полученное сообщение с использованием своего приватного ключа (stem:[c |-> D(d, c) = m])

== RSA алгоритм

*Rivest–Shamir–Adleman (RSA)* алгоритм основывается на проблеме факторизации (разложения на простые множители) чисел.

.Генерация ключей
* Выбирается два больших простых числа stem:[p] и stem:[q]
* Вычисляется stem:[n := p \cdot q] и вычисляется stem:[\varphi(n) = (p-1)(q-1)]
* Отыскивается число stem:[1 < e < \varphi(n)], которое будет взаимно просто с stem:[\varphi(n)]
* Вычисляют обратное для stem:[e] по модулю stem:[\varphi(n)]: stem:[d := e^{-1} mod \varphi(n)]

Тогда пара stem:[\langle e, n \rangle] -- публичный ключ, а stem:[\langle d, n \rangle] -- приватный.

.Алгоритмы шифрования
* stem:[E(\langle e, n \rangle, m) := m^e mod n]
* stem:[D(\langle d, n \rangle, c) := c^d mod n]

.Почему это работает
[%collapsible]
====
Пусть stem:[m \equiv 0 mod p]:
[stem]
++++
m^{ed} mod p = 0^{ed} mod p = 0
++++

Аналогично для stem:[q].

Иначе же это число не делится ни на одно из простых. Тогда по малой теореме Ферма
stem:[m^(p-1) = 1 mod p] и аналогично для stem:[q].

[stem]
++++
(m^e)^d = m^{1 + kn} = m(m^{k(p-1)(q-1)}) = m(m^{p-1})^{k(q-1)} = m mod p
++++

Откуда в обоих случаях мы получаем, что для системы

[latexmath]
++++
\begin{cases}
x \equiv m \pmod{p} \\
x \equiv m \pmod{q}
\end{cases}
++++

Найдены два решения: stem:[m] и stem:[m^{ed}]. Что по китайской теореме об остатках означает их сравнимость по модулю stem:[n = pq].
====

