= Цифровые подписи
:page-authors: Иван Калинин
:description: Цифровая подпись. DSA, ECDSA алгоритмы

Рассмотрим цифровые подписи основанные на асимметричном шифровании.

Для создания протокола асимметричного шифрования нужны следующие компоненты:

* stem:[k_{pub}] -- Публичный ключ
* stem:[k_{pr}] -- Приватный ключ
* stem:[H] -- Хеш-функция
* stem:[S] -- Функция подписи: stem:[S(k_{pr}, m) = s]
* stem:[V] -- Функция верификации: stem:[V(k_{pub}, s, d) \in \{\top, \bot\}]

Аналогично тому, как в шифровании мы требовали необратимость stem:[E] по приватному ключу, здесь мы требуем необратимость stem:[V].

Как работает протокол подписи:

. Генерируется пара stem:[\langle k_{pr}, k_{pub} \rangle]
. Публичный ключ stem:[k_{pub}] отправляется второму пользователю
. Первый пользователь вычисляет цифровую подпись для данных stem:[d]: stem:[s := S(k_{pr}, H(d))]
. Второй же пользователь при получении подписанных данных проверяет их подлинность (stem:[V(k_{pub}, s, d) \stackrel{?}{=} \top])

== DSA алгоритм

*Digital Signature Algorithm (DSA)* алгоритм основывается на проблеме логарифмировании чисел по модулю.

.Подготовка
* Фиксируем хеш-функцию, значения которой имеют разрядность stem:[N] бит
* Фиксируем простое число stem:[p] с такой же разрядностью
* Фиксируем простое число stem:[q] такое, чтобы stem:[q-1 \vdots p]
* Выбираем случайно число stem:[1 < h < q - 1] так, чтобы stem:[g := h^{\frac{q-1}{p}} mod q] не равнялось единице. Обычно, подходит значение stem:[h = 2].

.Генерация ключей
* Для приватного ключа случайно выбирают stem:[k_{pr} \in \{1,...,p-1\}]
* Публичный ключ вычисляют следующим образом: stem:[k_{pub}:= g^{k_{pr}} mod q]


.Подпись сообщения
* Выбираем случайный параметр stem:[r] для текущей подписи
* Вычисляем stem:[s_1 := (g^r mod q) mod p]
* Перегенерируем stem:[r], если stem:[s_1=0]
* Вычисляем stem:[s_2 := r^{-1}(H(d) + k_{pr} * s_1) mod p]
* Снова перегенерируем stem:[r], если stem:[s_2=0]
* Итоговая подпись -- это пара stem:[\langle s_1, s_2 \rangle]

.Верификация подписи
* Вычисляем stem:[x := s_2^{-1} mod p]
* Вычисляем stem:[y_1 := H(d)*x mod p]
* Вычисляем stem:[y_2 := s_1*x mod p]
* Проверяем, что stem:[(g^{y_1}k_{pub}^{y_2} mod q) mod p] это stem:[s_1]

.Почему это работает
// [%collapsible]
****
Из stem:[s_2 := r^{-1}(H(d) + k_{pr} * s_1) mod p] получим:

[stem]
++++
r = (H(d) + k_{pr} * s_1)s_2^{-1}

\text{ }\text{ } = H(d)s_2^{-1} + k_{pr} * s_1 * s_2^{-1}

\text{ }\text{ } = y_1 + k_{pr}y_2 mod p
++++

Последнее же означает, что stem:[r = y_1 + k_{pr}y_2 + pn] для некоторого stem:[n].

По малой теореме ферма stem:[g^p = g^(q-1) = 1 mod q].
Тогда имеем следующее:

[stem]
++++
g^r = g^{y_1 + k_{pr}y_2 + pn} = g^{y_1}g^{k_{pr}y_2}g^{pn}

\text{ }\text{ } = g^{y_1}g^{k_{pr}y_2}(g^p)^{n}

\text{ }\text{ } = g^{y_1}(g^{k_{pr}})^{y_2}(1)^{n}

\text{ }\text{ } = g^{y_1}k_{pub}^{y_2} mod q
++++

Навесим stem:[mod p] на обе части последнего равенства и получим необходимое.
****

== ECDSA алгоритм

На данный момент алгоритм DSA является не очень надежным, более надежной альтернативой являются алгоритмы, использующие <<el-curve,эллиптические кривые>> над конечными полями. Подобный алгоритм называется *Elliptic Curve Digital Signature Algorithm (ECDSA)*.

.Подготовка
* Фиксируем конечное поле stem:[\mathbb{F}_p] (поле остатков по простому модулю stem:[p])
* Фиксируем хеш-функцию, значения которой имеют разрядность такую же как у stem:[p]
* Выбираем случайно точку stem:[\mathcal{G}] на кривой

.Генерация ключей
* Для приватного ключа случайно выбираем stem:[k_{pr} \in \{1,...,p-1\}]
* Публичный ключ вычисляют следующим образом: stem:[k_{pub}:= k_{pr} \otimes \mathcal{G}]


.Подпись сообщения
* Выбираем случайный параметр stem:[r] для текущей подписи
* Вычисляем точку stem:[\langle x, y \rangle := r \otimes \mathcal{P}]
* Вычисляем stem:[s_1 := x mod p]
* Перегенерируем stem:[r], если stem:[s_1=0]
* Вычисляем stem:[s_2 := r^{-1}(H(d) + k_{pr} * s_1) mod p]

* Снова перегенерируем stem:[r], если stem:[s_2=0]
* Итоговая подпись -- это пара stem:[\langle s_1, s_2 \rangle]

.Верификация подписи
* Вычисляем stem:[x := s_2^{-1} mod p]
* Вычисляем stem:[y_1 := H(d)*x mod p]
* Вычисляем stem:[y_2 := s_1*x mod p]
* Находим точку stem:[\langle a, b \rangle := y_1 \otimes \mathcal{G} + y_2 \otimes k_{pub}]
* Проверяем, что stem:[a \equiv s_1 mod p]

> Как можно заметить, это почти что алгоритм DSA, только операции теперь не над числами, а над точками кривой.

.Почему это работает
****
Как и в прошлый раз раскроем коэффициенты в финальной точке:
[stem]
++++
y_1 \otimes \mathcal{G} + y_2 \otimes k_{pub}

\text{ }\text{ } = H(d)*x \otimes \mathcal{G} + s_1*x \otimes k_{pub}

\text{ }\text{ } = (H(d) + s_1*k_{pr})s_2^{-1} \otimes \mathcal{G}

\text{ }\text{ } = (H(d) + s_1*k_{pr})(r^{-1}(H(d) + k_{pr} * s_1))^{-1} \otimes \mathcal{G}

\text{ }\text{ } = (H(d) + s_1*k_{pr})(H(d) + s_1*k_{pr})^{-1}(r^{-1})^{-1} \otimes \mathcal{G}

\text{ }\text{ } = r \otimes \mathcal{G}
++++

Откуда, навесив stem:[mod p], и получим корректность.
****

== Read more

* xref:crypto/hash.adoc[Хэш функции]
[#el-curve]
* xref:crypto/el-curve.adoc[Эллиптические кривые]
* https://x25519.xargs.org[X25519 (C) Michael Driscoll]
* xref:utils/gpg.adoc[]
